<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="persona.asmxWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/persona.asmxWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/persona.asmxWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://tempuri.org/">
    <import location="http://localhost:60353/persona.asmx?WSDL" namespace="http://tempuri.org/"/>
    <plnk:partnerLinkType name="WebService1SoapLinkType">
        <plnk:role name="WebService1SoapRole" portType="ns:WebService1Soap"/>
    </plnk:partnerLinkType>
</definitions>
